//
// ReservationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ReservationsResponse: JSONEncodable {
    public var id: String?
    public var uuid: String?
    public var email: String?
    public var affiliate: String?
    public var name: String?
    public var referredCount: Int32?
    public var position: Int32?
    public var totalCount: Int32?
    public var activatedAt: NSDate?
    public var createdAt: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["uuid"] = self.uuid
        nillableDictionary["email"] = self.email
        nillableDictionary["affiliate"] = self.affiliate
        nillableDictionary["name"] = self.name
        nillableDictionary["referred_count"] = self.referredCount?.encodeToJSON()
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["total_count"] = self.totalCount?.encodeToJSON()
        nillableDictionary["activated_at"] = self.activatedAt?.encodeToJSON()
        nillableDictionary["created_at"] = self.createdAt?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
