//
// Reservation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Reservation: JSONEncodable {
    public var email: String?
    public var name: String?
    public var affiliate: String?
    public var responses: FormResponse?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["email"] = self.email
        nillableDictionary["name"] = self.name
        nillableDictionary["affiliate"] = self.affiliate
        nillableDictionary["responses"] = self.responses?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
