//
// SiteResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SiteResponse: JSONEncodable {
    public var id: String?
    public var brandColor: String?
    public var buttonTextColor: String?
    public var customStyles: String?
    public var askName: Bool?
    public var signupTitle: String?
    public var signupCopy: String?
    public var positionTitle: String?
    public var socialCopy: String?
    public var socialMessage: String?
    public var domain: String?
    public var shareSocialCopy: String?
    public var referralCopy: String?
    public var checkPositionCopy: String?
    public var joinButtonCopy: String?
    public var checkReservationCopy: String?
    public var emailFieldLabel: String?
    public var nameFieldLabel: String?
    public var thankYouShareTemplate: String?
    public var waitlistThreshold: Int32?
    public var useCustomThankYou: Bool?
    public var hideWaitlist: Bool?
    public var unmetSharedTemplate: String?
    public var thresholdMet: Bool?
    public var websiteUrl: String?
    public var trackingCode: String?
    public var customCss: String?
    public var hideBranding: Bool?
    public var totalCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["brand_color"] = self.brandColor
        nillableDictionary["button_text_color"] = self.buttonTextColor
        nillableDictionary["custom_styles"] = self.customStyles
        nillableDictionary["ask_name"] = self.askName
        nillableDictionary["signup_title"] = self.signupTitle
        nillableDictionary["signup_copy"] = self.signupCopy
        nillableDictionary["position_title"] = self.positionTitle
        nillableDictionary["social_copy"] = self.socialCopy
        nillableDictionary["social_message"] = self.socialMessage
        nillableDictionary["domain"] = self.domain
        nillableDictionary["share_social_copy"] = self.shareSocialCopy
        nillableDictionary["referral_copy"] = self.referralCopy
        nillableDictionary["check_position_copy"] = self.checkPositionCopy
        nillableDictionary["join_button_copy"] = self.joinButtonCopy
        nillableDictionary["check_reservation_copy"] = self.checkReservationCopy
        nillableDictionary["email_field_label"] = self.emailFieldLabel
        nillableDictionary["name_field_label"] = self.nameFieldLabel
        nillableDictionary["thank_you_share_template"] = self.thankYouShareTemplate
        nillableDictionary["waitlist_threshold"] = self.waitlistThreshold?.encodeToJSON()
        nillableDictionary["use_custom_thank_you"] = self.useCustomThankYou
        nillableDictionary["hide_waitlist"] = self.hideWaitlist
        nillableDictionary["unmet_shared_template"] = self.unmetSharedTemplate
        nillableDictionary["threshold_met"] = self.thresholdMet
        nillableDictionary["website_url"] = self.websiteUrl
        nillableDictionary["tracking_code"] = self.trackingCode
        nillableDictionary["custom_css"] = self.customCss
        nillableDictionary["hide_branding"] = self.hideBranding
        nillableDictionary["total_count"] = self.totalCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
